services:
  server:
    image: "grpc-backpr-srv:1"
    networks:
      - net
    ports:
      - "50051"
    mem_limit: 500m
  client:
    image: "grpc-backpr-clnt:1"
    networks:
      - net
    mem_limit: 500m
networks:
  net: