/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("grpc.backpressure.java-application-conventions")
}

dependencies {
    implementation(project(":utilities"))
    implementation(project(":proto"))
}

application {
    mainClass.set("grpc.backpressure.Server")
}

jib {
    to {
		image = "grpc-backpr-srv:1"
	}
}
