/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("grpc.backpressure.java-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.google.cloud.tools.jib")

}

jib {
    from {
        image = "eclipse-temurin:21-jre"
    }
    container {
        user = "nobody"
    }
}
